"$schema" = 'https://starship.rs/config-schema.json'
# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 200
# Replace the "â¯" symbol in the prompt with "âœ"
[character]
success_symbol = "[â¯](normal)[â¯](bold cyan)[â¯](green)"
error_symbol = "[â¯](red)[â¯](red)[â¯](red)"
#success_symbol = "[âœ](bold green)"
#error_symbol = "[âœ–](bold red) "


# ---- BATTERY ---- #
[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"
empty_symbol = "ğŸª«"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 20
style = "bold yellow"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[username]
style_user = "bold blue"
show_always = true

[time]
# disabled = false
use_12hr = true
# style = 

